version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dental-auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dental_auth
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - dental-network
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: dental-auth-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dental_auth
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dental-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: dental-auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dental-network
    restart: unless-stopped

networks:
  dental-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 